export const ROUTES = {
  AUTH: {
    ROOT: '/auth',
    LOGIN: '/login',
    SIGNUP: '/signup',
  },
  APP: {
    ROOT: '/app',
    DASHBOARD: '/app/dashboard',
    QUOTATIONS: '/app/quotations',
    QUOTATION_NEW: '/app/quotations/new',
    QUOTATION_DETAIL: (id: string = ':id') => `/app/quotations/${id}`,
    QUOTATION_APPROVAL: (id: string = ':id') => `/app/quotations/${id}/approval`,
    QUOTATION_FULFILLMENT: (id: string = ':id') => `/app/quotations/${id}/fulfillment`,
    QUOTATION_BILLING: (id: string = ':id') => `/app/quotations/${id}/billing`,
    PIPELINE: '/app/pipeline',
    PIPELINE_DETAIL: (id: string = ':dealId') => `/app/pipeline/${id}`,
    APPROVALS: '/app/approvals',
    APPROVAL_DETAIL: (id: string = ':id') => `/app/approvals/${id}`,
    CUSTOMERS: '/app/customers',
    PRODUCTS: '/app/products',
    PRODUCT_NEW: '/app/products/new',
    PRODUCT_DETAIL: (productId: string = ':productId') => `/app/products/${productId}`,
    PRODUCT_EDIT: (productId: string = ':productId') => `/app/products/${productId}/edit`,
    WAREHOUSES: '/app/warehouses',
    WAREHOUSE_DETAIL: (id: string = ':warehouseId') => `/app/warehouses/${id}`,
    FULFILLMENT: '/app/fulfillment',
    FULFILLMENT_DETAIL: (id: string = ':fulfillmentId') => `/app/fulfillment/${id}`,
    BILLING: '/app/billing',
    INVOICES: '/app/invoices',
    INVOICE_DETAIL: (id: string = ':invoiceId') => `/app/invoices/${id}`,
    SUBSCRIPTIONS: '/app/subscriptions',
    SUBSCRIPTION_DETAIL: (id: string = ':subscriptionId') => `/app/subscriptions/${id}`,
    DEAL_HEALTH: '/app/deal-health',
    DEAL_HEALTH_DETAIL: (dealId: string = ':dealId') => `/app/deal-health/${dealId}`,
    REPORTS: '/app/reports',
    ADMIN: '/app/admin',
    ADMIN_PRICING: '/app/admin/pricing',
    ADMIN_PRICING_RULES: '/app/admin/pricing/rules',
    ADMIN_PRICING_TIERS: '/app/admin/pricing/customer-tiers',
    ADMIN_USERS: '/app/admin/users',
    ADMIN_ROLES: '/app/admin/roles',
    ADMIN_SETTINGS: '/app/admin/settings',
    NOTIFICATIONS: '/app/notifications',
    AUDIT_LOGS: '/app/audit-logs',
  },
  PORTAL: {
    ROOT: '/portal',
    QUOTE: (token: string = ':token') => `/portal/quote/${token}`,
    NEGOTIATE: (token: string = ':token') => `/portal/quote/${token}/negotiate`,
    CONFIRMATION: (token: string = ':token') => `/portal/quote/${token}/confirmation`,
  },
};
